name: Create floating tags
author: Eshu
description: Create floating major and minor tags

runs:
  using: composite
  steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - shell: bash
      env:
        TAG: ${{ github.ref_name }}
      run: |
        set -euo pipefail
        
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
        
        MAJOR="${TAG%%.*}"
        git tag -fa "$MAJOR" -m "$MAJOR" "$TAG"^{}
        git push origin -f "$MAJOR"
        
        MINOR="${TAG%.*}"
        git tag -fa "$MINOR" -m "$MINOR" "$TAG"^{}
        git push origin -f "$MINOR"
