name: GitHub Workflows Linter
author: Eshu
description: GitHub workflows and actions linter

runs:
  using: composite
  steps:
    - name: Workflows and actions linter
      shell: bash
      run: |
        set -euo pipefail
        shopt -s globstar extglob nullglob
        WORKFLOWS=(**/workflows/**/*.y?(a)ml)
        mkdir -p ./bin
        go install github.com/rhysd/actionlint/cmd/actionlint@latest
        ./bin/actionlint -color -shellcheck=shellcheck "$@"
