name: Check Sonatype token
author: Eshu
description: Check if the Sonatype token is valid

inputs:
  username:
    description: "Sonatype Central username"
    required: true
  password:
    description: "Sonatype Central password"
    required: true

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        AUTH="Bearer $(printf "%s:%s" "${{ inputs.username }}" "${{ inputs.password }}" | base64)"
        URL=https://central.sonatype.com/api/v1/publisher/status?id=0
        code=$(curl -sS -w '%{http_code}' -o /dev/null -H "Authorization: $AUTH" -X POST "$URL")
        echo "Code: $code"
        case "$code" in
          401)
            echo "Sonatype credentials are INVALID (401 Unauthorized)" >&2
            exit 1
            ;;
          200|400|404)
            echo "Sonatype credentials look OK (no 401)."
            ;;
          *)
            echo "Unexpected response: $code; treating as failure." >&2
            exit 1
            ;;
        esac
