name: Floating tags

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  floating-tags:
    runs-on: ubuntu-latest
    steps:
      - uses: h8io/gha/actions/floating-tags@master
