name: GitHub Actions and Workflows Linter

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

permissions:
  contents: read
  pull-requests: read

jobs:
  linter:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v5
      - shell: bash
        run: |
          set -euo pipefail
          shopt -s globstar extglob nullglob

          WORKFLOWS=(.github/workflows/**/*.y?(a)ml)
          echo "${WORKFLOWS[@]}"
          mkdir -p ./bin
          curl -sSfL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash \
            | bash -s -- latest ./bin
          ./bin/actionlint -color -shellcheck=shellcheck "${WORKFLOWS[@]}"

          ACTIONS=(./actions/**/action.y?(a)ml)
          if ((${#ACTIONS[@]} == 0)); then
            echo "No composite actions found; skipping validation." >&2
            exit 1
          else
            for ACTION in "${ACTIONS[@]}"; do
              echo "Validating $ACTION"
              npx --yes @action-validator/cli "$ACTION"
            done
          fi
