name: GitHub Actions and Workflows Linter

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v5
      - uses: h8io/gha/workflows-linter@master
      - shell: bash
        run: |
          set -euo pipefail
          shopt -s globstar extglob nullglob
          ACTIONS=(./*/action.y?(a)ml)
          if ((${#ACTIONS[@]} == 0)); then
            echo "No composite actions found; skipping validation." >&2
            exit 1
          else
            for ACTION in "${ACTIONS[@]}"; do
              echo "Validating $f"
              npx --yes @action-validator/cli "$ACTION"
            done
          fi
